# Site settings
title: David James
description: Portfolio Site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: David A. James
user_description: Hello! I'm David James, a passionate graduate student at UCLA studying Geophysics and Space Physics where my research consists of looking at the outer planets in our Solar System. My background in computer science and mathematics has led me to be an amateur educator on Youtube to help others and to (hopefully) help me with teaching and learning these topics. Please feel free to reach out!
user_title: Graduate Student Researcher
email: davidabraham@ucla.edu

exclude: ['package.json', 'src' , 'node_modules']
